# Generated by Django 4.2.2 on 2023-06-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('id_finanzas', models.AutoField(primary_key=True, serialize=False)),
                ('dinero_capital', models.IntegerField(null=True)),
                ('id_gastos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.gastos')),
            ],
        ),
    ]
