# Generated by Django 3.2 on 2023-11-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmovement',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
