# Generated by Django 3.2 on 2023-11-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_walletmovement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmovement',
            name='type',
            field=models.CharField(choices=[('entry', 'Ingreso'), ('exit', 'Gasto'), ('loan_out', 'Salida por prestamo'), ('loan_in', 'Entrada por prestamo'), ('admin_charge', 'Recarga de administracion')], default='deposit', max_length=255),
        ),
    ]
