# Generated by Django 3.2 on 2023-11-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_walletmovement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmovement',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='walletmovement',
            name='last_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
