# Generated by Django 3.2 on 2023-11-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounting', '0005_auto_20231107_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmovement',
            name='proof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uploadedfiles'),
        ),
    ]
