# Generated by Django 3.2 on 2023-11-07 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0006_walletmovement_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incomes', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('collected', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('loans', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('final_balance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('not_collected', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('customers_not_collected', models.IntegerField(default=0)),
                ('customers_collected', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DailyCheckouts',
                'db_table': 'daily_checkouts',
            },
        ),
    ]
