# Generated by Django 3.2 on 2023-11-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20231107_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodClosures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'PeriodClosures',
                'db_table': 'period_closures',
                'ordering': ['-id'],
            },
        ),
    ]
