# Generated by Django 3.2 on 2024-06-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_periodclosures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmovement',
            name='type',
            field=models.CharField(choices=[('entry', 'Ingreso'), ('exit', 'Gasto'), ('loan_out', 'Salida por prestamo'), ('loan_in', 'Entrada por prestamo'), ('admin_charge', 'Recarga de administracion'), ('new_loan', 'Nuevo prestamo')], default='deposit', max_length=255),
        ),
    ]
