# Generated by Django 3.2 on 2024-06-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_walletmovement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckout',
            name='period',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='accounting.periodclosures'),
            preserve_default=False,
        ),
    ]
