# Generated by Django 3.2 on 2024-06-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_dailycheckout_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletmovement',
            name='type',
            field=models.CharField(choices=[('entry', 'Ingreso'), ('exit', 'Gasto'), ('loan_out', 'Salida por prestamo'), ('loan_in', 'Entrada por prestamo'), ('admin_charge', 'Recarga de administracion'), ('new_loan', 'Nuevo prestamo'), ('positive_delete_loan', 'Eliminacion de prestamo positivo'), ('negative_delete_loan', 'Eliminacion de prestamo negativo')], default='deposit', max_length=255),
        ),
    ]
