# Generated by Django 3.2 on 2024-06-26 03:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0013_usergoals'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergoals',
            unique_together={('user', 'period_closure')},
        ),
    ]
