runtime: python39
entrypoint: gunicorn -b :$PORT CreditoXD.wsgi:application

instance_class: F2

env_variables:
  # Agrega aquí tus variables de entorno si las necesitas

automatic_scaling:
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
