# Generated by Django 3.2 on 2023-11-05 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('home_address', models.CharField(max_length=255, null=True)),
                ('business_name', models.CharField(max_length=255, null=True)),
                ('business_address', models.CharField(max_length=255, null=True)),
                ('cell_phone_number', models.CharField(max_length=255, null=True)),
                ('occupation', models.CharField(max_length=255, null=True)),
                ('alias_or_reference', models.CharField(max_length=255, null=True)),
                ('business_location', models.CharField(max_length=255, null=True)),
                ('home_location', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_document', to='core.uploadedfiles')),
                ('business_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_photo', to='core.uploadedfiles')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('debt_collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_collector', to=settings.AUTH_USER_MODEL)),
                ('identity_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_document', to='core.uploadedfiles')),
                ('who_referred', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.customer')),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.02, max_digits=5)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('recurrence', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('biweekly', 'biweekly'), ('monthly', 'monthly')], default='daily', max_length=255)),
                ('dues', models.IntegerField(null=True)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('interest_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('principal_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dues_paid', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.customer')),
            ],
            options={
                'verbose_name_plural': 'Loans',
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loan')),
            ],
            options={
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
    ]
