# Generated by Django 3.2 on 2023-11-05 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
