# Generated by Django 3.2 on 2023-11-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='document_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
