# Generated by Django 3.2 on 2023-11-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_customer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cell_phone_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
