# Generated by Django 3.2 on 2023-11-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20231105_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
