# Generated by Django 3.2 on 2023-11-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_customer_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='recurrence',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='daily', max_length=255),
        ),
    ]
