# Generated by Django 3.2 on 2023-11-07 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loan_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LoanMarkdowns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('markdown', models.BooleanField(default=False)),
                ('apply_to_date', models.DateField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
            ],
            options={
                'verbose_name_plural': 'LoanMarkdowns',
                'db_table': 'loan_markdowns',
            },
        ),
    ]
