# Generated by Django 3.2 on 2023-11-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20231107_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmarkdowns',
            name='apply_to_date',
            field=models.DateField(null=True),
        ),
    ]
