# Generated by Django 3.2 on 2023-11-07 03:08

import app.loans.models.loans
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_loanmarkdowns_apply_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=app.loans.models.loans.get_current_date),
        ),
    ]
