# Generated by Django 3.2 on 2023-11-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_auto_20231107_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
