# Generated by Django 3.2 on 2024-04-08 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_auto_20231123_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
