# Generated by Django 3.2 on 2024-05-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240503_1946'),
        ('loans', '0015_alter_loan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='core.uploadedfiles'),
        ),
    ]
