# Generated by Django 3.2 on 2024-05-06 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0016_customer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector', to=settings.AUTH_USER_MODEL),
        ),
    ]
