# Generated by Django 3.2 on 2024-05-06 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0017_loan_collector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='debt_collector',
        ),
        migrations.AddField(
            model_name='customer',
            name='debt_collector',
            field=models.ManyToManyField(related_name='debt_collector', to=settings.AUTH_USER_MODEL),
        ),
    ]
