# Generated by Django 3.2 on 2024-06-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_auto_20240506_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='debt_collector',
        ),
    ]
