# Generated by Django 3.2 on 2024-06-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_remove_customer_debt_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_clavo',
            field=models.BooleanField(default=False),
        ),
    ]
