# Generated by Django 4.2.2 on 2023-06-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('estado_empleado', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('numero_celular_1', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('fecha_inicio', models.DateField()),
            ],
        ),
    ]
