# Generated by Django 4.2.2 on 2023-07-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleados",
            name="cedula",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
