# Generated by Django 4.2.2 on 2023-07-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_alter_empleados_cedula"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empleados",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="empleados",
            name="contraseña",
        ),
        migrations.RemoveField(
            model_name="empleados",
            name="email",
        ),
        migrations.RemoveField(
            model_name="empleados",
            name="estado_empleado",
        ),
        migrations.RemoveField(
            model_name="empleados",
            name="nombre",
        ),
        migrations.AlterField(
            model_name="empleados",
            name="fecha_inicio",
            field=models.DateField(auto_now_add=True),
        ),
    ]
