# Generated by Django 4.2.2 on 2023-07-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0004_empleados_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleados",
            name="id_empleado",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="empleados.Empleados"
            ),
        ),
    ]
