from .customer_loan import CustomerLoanAPIView
from .customers import CustomerBasicListAPIView, AllcustomersBasicListAPIView
from .loans import LoanBasicListAPIView, LoanFullListAPIView
from .payments import CreatePaymentAPIView
from .ordering import UpdateLoanOrderingAPIView
from .markdowns import LoanMarkdownsCreateAPIView, LoanMarkdownsListAPIView