# Generated by Django 4.2.2 on 2023-06-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('saldo_a_cobrar', models.IntegerField(null=True)),
                ('valor_cobrado', models.IntegerField(null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
    ]
