# Generated by Django 4.2.2 on 2023-07-01 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='id_empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados'),
        ),
    ]
