# Generated by Django 4.2.2 on 2023-07-23 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_alter_empleados_cedula"),
        ("rutas", "0002_rutas_id_empleado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rutas",
            name="id_cliente",
        ),
        migrations.AlterField(
            model_name="rutas",
            name="id_empleado",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empleados.empleados",
            ),
        ),
    ]
