# Generated by Django 4.2.2 on 2023-07-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0003_remove_rutas_id_cliente_alter_rutas_id_empleado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rutas",
            name="saldo_a_cobrar",
        ),
        migrations.RemoveField(
            model_name="rutas",
            name="valor_cobrado",
        ),
    ]
