# Generated by Django 4.2.3 on 2023-07-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0005_alter_empleados_id_empleado"),
        ("rutas", "0004_remove_rutas_saldo_a_cobrar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rutas",
            name="id_empleado",
            field=models.OneToOneField(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="empleados.empleados",
            ),
        ),
    ]
