# Generated by Django 4.2.3 on 2023-08-06 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleados_id_empleado'),
        ('rutas', '0005_alter_rutas_id_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='id_empleado',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados'),
        ),
    ]
