# Generated by Django 3.2 on 2023-11-05 01:17

import app.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(default='media/default', upload_to=app.core.models.upload_to, verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('customer_images', 'customer_images')], default='other', max_length=255)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UploadedFiles',
                'db_table': 'uploaded_files',
            },
        ),
    ]
