# Generated by Django 3.2 on 2024-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_infoandrules'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CustomConfig',
                'db_table': 'custom_config',
            },
        ),
    ]
