# Generated by Django 4.2.2 on 2023-06-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('estado_cliente', models.IntegerField(choices=[(1, 'activo'), (2, 'desactivado')])),
                ('estado_credito', models.IntegerField(choices=[(1, 'excelente'), (2, 'bien'), (3, 'mal'), (4, 'muy_mal')], null=True)),
                ('nacionalidad', models.CharField(max_length=15)),
                ('nacimiento', models.DateField()),
                ('direccion_1', models.CharField(max_length=30)),
                ('direccion_2', models.CharField(max_length=30, null=True)),
                ('numero_celular_1', models.CharField(max_length=10)),
                ('numero_celular_2', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ruta', models.CharField(max_length=20)),
                ('cuota_diaria', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
