# Generated by Django 4.2.2 on 2023-07-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientes",
            name="cuota_diaria",
        ),
        migrations.RemoveField(
            model_name="clientes",
            name="saldo",
        ),
    ]
