# Generated by Django 4.2.2 on 2023-07-23 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0003_remove_rutas_id_cliente_alter_rutas_id_empleado"),
        ("clientes", "0002_remove_clientes_cuota_diaria_remove_clientes_saldo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="ruta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rutas.rutas",
            ),
        ),
    ]
