# Generated by Django 4.2.2 on 2023-07-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_alter_clientes_ruta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="id_cliente",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="clientes.Clientes"
            ),
        ),
    ]
