# Generated by Django 4.2.3 on 2023-08-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_clientes_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='numero_celular_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
