# Generated by Django 4.2.3 on 2023-08-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_clientes_direccion_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado_cliente',
            field=models.IntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=0),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado_credito',
            field=models.IntegerField(choices=[(1, 'Excelente'), (2, 'Bueno'), (3, 'Regular'), (4, 'Malo'), (5, 'Muy Malo')], default=2),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nacionalidad',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='numero_celular_1',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
