# Generated by Django 4.2.3 on 2023-10-23 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_clientes_ruta_clientes_empleado_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.CharField(choices=[('old', 'Antiguo'), ('new', 'Nuevo')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='clientes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
