# Generated by Django 4.2.2 on 2023-06-24 05:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditos',
            fields=[
                ('id_credito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_dias', models.IntegerField(default=0)),
                ('interes', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)])),
                ('fecha_inicio', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
            ],
        ),
    ]
