# Generated by Django 4.2.2 on 2023-07-23 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("creditos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditos",
            name="valor_credito",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
