# Generated by Django 4.2.2 on 2023-07-23 05:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_alter_empleados_cedula"),
        ("creditos", "0002_creditos_valor_credito"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditos",
            name="credito_finalizado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="creditos",
            name="cuota_diaria",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="creditos",
            name="cuotas_pagadas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="creditos",
            name="fecha_finalizacion_estimada",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="creditos",
            name="fecha_finalizacion_real",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="creditos",
            name="cantidad_dias",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="creditos",
            name="interes",
            field=models.IntegerField(
                default=20, validators=[django.core.validators.MaxValueValidator(99)]
            ),
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("monto_pago", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pagado_completo", models.BooleanField(default=False)),
                ("numero_cuota", models.PositiveIntegerField()),
                ("cuotas_pendientes", models.PositiveIntegerField()),
                ("fecha_actualizacion", models.DateField(auto_now=True, null=True)),
                (
                    "credito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payments",
                        to="creditos.creditos",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="empleados.empleados",
                    ),
                ),
            ],
        ),
    ]
