# Generated by Django 4.2.2 on 2023-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditos", "0003_creditos_credito_finalizado_creditos_cuota_diaria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="monto_esperado",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
