# Generated by Django 4.2.2 on 2023-07-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditos", "0004_payments_monto_esperado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="monto_pago",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
