# Generated by Django 4.2.2 on 2023-07-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditos", "0005_alter_payments_monto_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditos",
            name="fecha_finalizacion_real",
            field=models.DateField(null=True),
        ),
    ]
