# Generated by Django 4.2.3 on 2023-08-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_creditos_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditos',
            name='id_empleado',
        ),
    ]
