# Generated by Django 4.2.3 on 2023-08-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0009_payments_ruta_alter_payments_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='fecha_actualizacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
