# Generated by Django 4.2.2 on 2023-06-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id_gastos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_gasto', models.DateField()),
                ('valor_gasto', models.CharField(max_length=20)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
            ],
        ),
    ]
